Pz 1.6 done
ProgramDig/practicalAnokhin pull request #1
Opened 2022-01-25 10:46 UTC by ProgramDig

2022-01-28 12:12 UTC, oleksvlas requested changes
Все дуже добре, позабираєш лишні відступи, відправиш і я підтверджу!!!!

2022-01-28 12:12 UTC, oleksvlas commented on pz_1.6/html/gitcomand.html
> +	<meta name="viewport" content="width=device-width, initial-scale=1.0">
позабирай лишні відступи, вони роблять файл важчим.

2022-01-28 12:38 UTC, ProgramDig commented on pz_1.6/html/gitcomand.html
> +	<meta name="viewport" content="width=device-width, initial-scale=1.0">
відступи зараз ззаберу

2022-02-01 08:57 UTC, oleksvlas approved these changes

2022-02-01 08:57 UTC, merged

2022-02-01 08:58 UTC, oleksvlas commented
Зараховано!!!